use evmora_compiler::Compiler;
use anyhow::Result;

fn main() -> Result<()> {
    let compiler = Compiler::new();
    
    println!("--- Quorlin Compilation ---");
    let ql_source = std::fs::read_to_string("tests/fixtures/contracts/token.ql")?;
    let ql_bytecode = compiler.compile(&ql_source, "ql")?;
    println!("Parsed Quorlin Source length: {}", ql_source.len());
    println!("Generated Bytecode length: {}", ql_bytecode.len());
    println!("Bytecode sample: {}", hex::encode(&ql_bytecode[0..std::cmp::min(20, ql_bytecode.len())]));
    
    println!("\n--- Solidity Compilation ---");
    let sol_source = std::fs::read_to_string("tests/fixtures/contracts/Token.sol")?;
    let sol_bytecode = compiler.compile(&sol_source, "sol")?;
    println!("Parsed Solidity Source length: {}", sol_source.len());
    println!("Generated Bytecode length: {}", sol_bytecode.len());
    println!("Bytecode sample: {}", hex::encode(&sol_bytecode[0..std::cmp::min(20, sol_bytecode.len())]));

    println!("\n--- Vyper Compilation ---");
    let vy_source = std::fs::read_to_string("tests/fixtures/contracts/QuorlinToken.vy")?;
    let vy_bytecode = compiler.compile(&vy_source, "vy")?;
    println!("Parsed Vyper Source length: {}", vy_source.len());
    println!("Generated Bytecode length: {}", vy_bytecode.len());
    println!("Bytecode sample: {}", hex::encode(&vy_bytecode[0..std::cmp::min(20, vy_bytecode.len())]));

    println!("\n--- Move Compilation ---");
    let move_source = std::fs::read_to_string("tests/fixtures/contracts/quorlin_token.move")?;
    let move_bytecode = compiler.compile(&move_source, "move")?;
    println!("Parsed Move Source length: {}", move_source.len());
    println!("Generated Bytecode length: {}", move_bytecode.len());
    println!("Bytecode sample: {}", hex::encode(&move_bytecode[0..std::cmp::min(20, move_bytecode.len())]));

    Ok(())
}
